name: Make image interlace
on:
  push:
    branches:
      - master
      - main
jobs:
  createImageInterlacePR:
    runs-on: ubuntu-latest
    steps:
      - uses: hanhan9449/img-interlace-action@main
