name: Make image interlace
on:
  push:
    branches:
      - master
      - main

jobs:
  createImageInterlacePR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hanhan9449/img-interlace-action@main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "feat: make image interlace"
          title: "[AutoCreate]使图片交错 make image interlace"
          body: "图片交错编码，能够更快的下载展示"
          branch: autocreate/image-interlace
          
